import Home from "@/components/Home/Home";
import Image from "next/image";

export const metadata = {
  title: "Modern Sadhu",
  description: "Generated by create next app",
};

export default function Page() {

  return (
    <div className={'home'} >
      <Home />
    </div>
  );
}
